# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlexpander2', '0002_url_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='is_favorite',
        ),
        migrations.AlterField(
            model_name='url',
            name='status',
            field=models.IntegerField(),
        ),
    ]
