# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlexpander2', '0003_auto_20160808_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='snapshot_url',
            field=models.CharField(default='http://google.com', max_length=1000),
        ),
        migrations.AddField(
            model_name='url',
            name='timestamp',
            field=models.CharField(default='1234567', max_length=15),
        ),
    ]
